"""Differentiable particle-mesh components for long-range MACE extensions."""

from .calculators import MACEFNOCalculator
from .coupling import (
    FrozenMACEFeatures,
    MACEFNOResidual,
    NeutralLatentHead,
    energy_force_loss,
    mace_invariant_indices,
)
from .fno import (
    FNO2D,
    FNO3D,
    FNOFieldOperator2D,
    FNOFieldOperator3D,
    GlobalZMixing,
    LinearFNO2D,
    LinearFNO3D,
    LinearSlabFNO2D,
    MetricEqGINOSpectralConv3D,
    SlabFNO2D,
    SlabFNOFieldOperator2D,
    SlabPlanarSpectralConv2D,
    SlabSpectralConv2D,
    SpectralConv2D,
    SpectralConv3D,
)
from .model import (
    LearnedParticleMeshLongRange,
    LearnedParticleMeshLongRange3D,
    LearnedSlabParticleMeshLongRange,
    ParticleMeshEnergy,
    ParticleMeshEnergy3D,
    ParticleMeshLongRange,
    SlabParticleMeshEnergy,
)
from .particle_mesh import (
    PeriodicParticleMesh2D,
    PeriodicParticleMesh3D,
    SlabParticleMesh,
)
from .reference import direct_planar_coulomb_energy
from .spectral import (
    PlanarCoulombOperator,
    mesh_interaction_energy,
    mesh_interaction_energy_3d,
    slab_mesh_interaction_energy,
)
from .spectral_response import (
    fit_anisotropic_inverse_quadratic_response,
    fit_power_law_response,
    fit_reference_power_response,
    planar_wavevector,
    quadratic_basis_response,
    quadratic_mode_response,
    slab_coulomb_profile_matrix,
    slab_z_profiles,
    unique_integer_modes,
    unique_integer_modes_2d,
    unit_rms_cosine_mode,
    unit_rms_cosine_mode_2d,
    wavevector,
    wavevector_norm,
)
from .symmetry import (
    cubic_signed_permutation_matrices,
    is_cubic_cell,
    transform_in_cell_axis_basis,
)
from .synthetic import generate_planar_coulomb_fields

__all__ = [
    "FNO2D",
    "FNO3D",
    "FNOFieldOperator2D",
    "FNOFieldOperator3D",
    "GlobalZMixing",
    "FrozenMACEFeatures",
    "LearnedParticleMeshLongRange",
    "LearnedSlabParticleMeshLongRange",
    "LearnedParticleMeshLongRange3D",
    "LinearFNO2D",
    "LinearFNO3D",
    "LinearSlabFNO2D",
    "MACEFNOResidual",
    "MACEFNOCalculator",
    "MetricEqGINOSpectralConv3D",
    "NeutralLatentHead",
    "ParticleMeshEnergy",
    "SlabParticleMeshEnergy",
    "ParticleMeshEnergy3D",
    "ParticleMeshLongRange",
    "PeriodicParticleMesh2D",
    "PeriodicParticleMesh3D",
    "PlanarCoulombOperator",
    "SlabFNO2D",
    "SlabFNOFieldOperator2D",
    "SlabPlanarSpectralConv2D",
    "SlabSpectralConv2D",
    "SpectralConv2D",
    "SpectralConv3D",
    "SlabParticleMesh",
    "direct_planar_coulomb_energy",
    "cubic_signed_permutation_matrices",
    "energy_force_loss",
    "fit_anisotropic_inverse_quadratic_response",
    "fit_power_law_response",
    "fit_reference_power_response",
    "generate_planar_coulomb_fields",
    "is_cubic_cell",
    "mace_invariant_indices",
    "mesh_interaction_energy",
    "mesh_interaction_energy_3d",
    "planar_wavevector",
    "quadratic_basis_response",
    "quadratic_mode_response",
    "slab_coulomb_profile_matrix",
    "slab_mesh_interaction_energy",
    "slab_z_profiles",
    "transform_in_cell_axis_basis",
    "unique_integer_modes",
    "unique_integer_modes_2d",
    "unit_rms_cosine_mode",
    "unit_rms_cosine_mode_2d",
    "wavevector",
    "wavevector_norm",
]
