"""Frozen-MACE coupling for an energy-conserving particle-mesh residual."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any

import torch
from torch import Tensor, nn

from .model import (
    LearnedParticleMeshLongRange,
    LearnedParticleMeshLongRange2p5D,
    LearnedParticleMeshLongRange3D,
)
from .symmetry import is_cubic_cell


def _product_output_irreps(product: nn.Module) -> Any:
    """Return the output irreps exposed by common MACE product blocks."""
    candidates = (
        getattr(getattr(product, "linear", None), "irreps_out", None),
        getattr(product, "irreps_out", None),
        getattr(product, "target_irreps", None),
        getattr(getattr(product, "symmetric_contractions", None), "irreps_out", None),
    )
    for irreps in candidates:
        if irreps is not None and hasattr(irreps, "slices"):
            return irreps
    raise TypeError(
        "could not find output irreps on a MACE product block; pass "
        "invariant_indices explicitly for this MACE variant"
    )


def mace_invariant_indices(mace_model: nn.Module) -> tuple[list[int], int]:
    """Locate all even scalar (``0e``) columns in MACE's ``node_feats``.

    MACE concatenates the product output from every interaction layer. This
    function follows the same layer order and uses each product's e3nn irreps
    metadata, rather than assuming that every layer has the same layout.

    Returns:
        A list of invariant column indices and the full descriptor dimension.
    """
    products = getattr(mace_model, "products", None)
    if products is None or len(products) == 0:
        raise TypeError(
            "the backbone does not expose MACE product blocks; pass "
            "invariant_indices explicitly"
        )

    indices: list[int] = []
    offset = 0
    for product in products:
        irreps = _product_output_irreps(product)
        for (_, irrep), component_slice in zip(irreps, irreps.slices()):
            if int(irrep.l) == 0 and int(irrep.p) == 1:
                indices.extend(
                    range(
                        offset + int(component_slice.start),
                        offset + int(component_slice.stop),
                    )
                )
        offset += int(irreps.dim)

    if not indices:
        raise ValueError("the MACE backbone has no even scalar (0e) node features")
    return indices, offset


class FrozenMACEFeatures(nn.Module):
    """Run a frozen MACE backbone and retain its invariant node features.

    Backbone parameters are frozen, but the forward pass deliberately does not
    use ``torch.no_grad`` and does not detach the descriptors. The derivatives
    of the descriptors with respect to atomic positions are part of the force
    generated by the residual branch.
    """

    def __init__(
        self,
        mace_model: nn.Module,
        *,
        invariant_indices: Sequence[int] | None = None,
    ) -> None:
        super().__init__()
        self.mace_model = mace_model
        for parameter in self.mace_model.parameters():
            parameter.requires_grad_(False)
        self.mace_model.eval()

        atomic_energies = getattr(
            getattr(self.mace_model, "atomic_energies_fn", None),
            "atomic_energies",
            None,
        )
        if atomic_energies is None:
            atomic_energies = torch.empty(0, dtype=torch.float64)
        self.register_buffer(
            "atomic_energies_reference",
            torch.atleast_2d(atomic_energies.detach().clone()).to(torch.float64),
        )

        if invariant_indices is None:
            indices, descriptor_dim = mace_invariant_indices(self.mace_model)
        else:
            indices = [int(index) for index in invariant_indices]
            if not indices or min(indices) < 0 or len(set(indices)) != len(indices):
                raise ValueError(
                    "invariant_indices must contain distinct non-negative integers"
                )
            descriptor_dim = max(indices) + 1
        self.descriptor_dim = int(descriptor_dim)
        self.register_buffer(
            "invariant_indices", torch.tensor(indices, dtype=torch.long)
        )

    @property
    def feature_dim(self) -> int:
        return int(self.invariant_indices.numel())

    def train(self, mode: bool = True) -> FrozenMACEFeatures:
        super().train(mode)
        self.mace_model.eval()
        return self

    def _apply(self, fn: Any, recurse: bool = True) -> FrozenMACEFeatures:
        """Move the module while retaining exact atomic energies in float64."""
        atomic_reference = self.atomic_energies_reference
        super()._apply(fn, recurse=recurse)
        self.atomic_energies_reference = atomic_reference.to(
            device=self.invariant_indices.device,
            dtype=torch.float64,
        )
        return self

    def corrected_base_energy(
        self,
        data: Mapping[str, Tensor],
        output: Mapping[str, Tensor | None],
    ) -> Tensor:
        """Accumulate large atomic references in float64 for mixed precision."""
        energy = output.get("energy")
        if energy is None:
            raise KeyError("the MACE output does not contain energy")
        if energy.dtype == torch.float64 or self.atomic_energies_reference.numel() == 0:
            return energy

        node_attrs = data["node_attrs"]
        batch = data["batch"].to(torch.long)
        num_graphs = int(energy.numel())
        graph_heads = (
            data.get(
                "head",
                torch.zeros(num_graphs, dtype=torch.long, device=batch.device),
            )
            .reshape(-1)
            .to(torch.long)
        )
        if graph_heads.numel() != num_graphs:
            raise ValueError("head must contain one MACE head index per graph")
        node_heads = graph_heads.index_select(0, batch)

        exact_all = torch.matmul(
            node_attrs.to(torch.float64),
            self.atomic_energies_reference.transpose(0, 1),
        )
        exact_node = exact_all.gather(1, node_heads[:, None]).squeeze(1)
        exact_e0 = exact_node.new_zeros(num_graphs).index_add(0, batch, exact_node)

        interaction_energy = output.get("interaction_energy")
        if interaction_energy is not None:
            return exact_e0 + interaction_energy.to(torch.float64)

        contributions = output.get("contributions")
        if contributions is not None:
            approximate_all = self.mace_model.atomic_energies_fn(node_attrs)
            approximate_node = approximate_all.gather(1, node_heads[:, None]).squeeze(1)
            approximate_e0 = approximate_node.new_zeros(num_graphs).index_add(
                0, batch, approximate_node
            )
            non_atomic = contributions.to(torch.float64)
            non_atomic = (
                non_atomic[:, 0]
                - approximate_e0.to(torch.float64)
                + non_atomic[:, 1:].sum(dim=1)
            )
            return exact_e0 + non_atomic

        # Fallback for uncommon MACE variants that expose neither separated
        # interactions nor contributions. This restores the reference offset,
        # although a float32 total may already have rounded its interaction.
        approximate_all = self.mace_model.atomic_energies_fn(node_attrs)
        approximate_node = approximate_all.gather(1, node_heads[:, None]).squeeze(1)
        approximate_e0 = approximate_node.new_zeros(num_graphs).index_add(
            0, batch, approximate_node
        )
        return energy.to(torch.float64) + exact_e0 - approximate_e0.to(torch.float64)

    def forward(
        self, data: Mapping[str, Tensor]
    ) -> tuple[Tensor, Tensor, Mapping[str, Tensor | None]]:
        output = self.mace_model(
            data,
            training=False,
            compute_force=False,
            compute_virials=False,
            compute_stress=False,
            compute_displacement=False,
            compute_hessian=False,
        )
        if "node_feats" not in output or output["node_feats"] is None:
            raise KeyError("the MACE output does not contain node_feats")
        if "energy" not in output or output["energy"] is None:
            raise KeyError("the MACE output does not contain energy")

        node_features = output["node_feats"]
        if node_features.ndim != 2:
            raise ValueError("MACE node_feats must have shape (n_atoms, features)")
        if node_features.shape[1] < self.descriptor_dim:
            raise ValueError(
                "MACE returned fewer descriptor columns than expected: "
                f"{node_features.shape[1]} < {self.descriptor_dim}"
            )
        invariants = node_features.index_select(1, self.invariant_indices)
        return self.corrected_base_energy(data, output), invariants, output


class NeutralLatentHead(nn.Module):
    """Map invariant atom features to graph-wise neutral scalar channels."""

    def __init__(
        self,
        feature_dim: int,
        channels: int,
        *,
        hidden_channels: int = 64,
    ) -> None:
        super().__init__()
        if min(feature_dim, channels, hidden_channels) < 1:
            raise ValueError("all feature and channel dimensions must be positive")
        self.feature_dim = int(feature_dim)
        self.channels = int(channels)
        self.network = nn.Sequential(
            nn.LayerNorm(feature_dim),
            nn.Linear(feature_dim, hidden_channels),
            nn.SiLU(),
            nn.Linear(hidden_channels, channels, bias=False),
        )

    def forward(self, features: Tensor, batch: Tensor) -> Tensor:
        if features.ndim != 2 or features.shape[1] != self.feature_dim:
            raise ValueError(f"features must have shape (n_atoms, {self.feature_dim})")
        if batch.ndim != 1 or batch.shape[0] != features.shape[0]:
            raise ValueError("batch must have shape (n_atoms,)")
        if batch.dtype != torch.long:
            raise TypeError("batch must use torch.long indices")
        if batch.numel() == 0:
            raise ValueError("at least one atom is required")

        raw = self.network(features)
        num_graphs = int(batch.max().detach().cpu()) + 1
        sums = raw.new_zeros((num_graphs, self.channels)).index_add(0, batch, raw)
        counts = raw.new_zeros((num_graphs, 1)).index_add(
            0, batch, raw.new_ones((raw.shape[0], 1))
        )
        if bool((counts == 0).any().detach().cpu()):
            raise ValueError("batch graph indices must be consecutive and non-empty")
        return raw - (sums / counts)[batch]


def _graph_cells(cell: Tensor, num_graphs: int) -> Tensor:
    if cell.ndim == 2 and cell.shape == (3, 3) and num_graphs == 1:
        return cell.unsqueeze(0)
    if cell.ndim == 3 and cell.shape == (num_graphs, 3, 3):
        return cell
    if cell.ndim == 2 and cell.shape == (3 * num_graphs, 3):
        return cell.reshape(num_graphs, 3, 3)
    raise ValueError(
        "cell must have shape (3, 3), (n_graphs, 3, 3), or " "(3*n_graphs, 3)"
    )


def _negative_energy_gradient(
    energy: Tensor,
    positions: Tensor,
    *,
    create_graph: bool,
    retain_graph: bool,
) -> Tensor:
    gradient = torch.autograd.grad(
        energy.sum(),
        positions,
        create_graph=create_graph,
        retain_graph=retain_graph,
        allow_unused=True,
    )[0]
    if gradient is None:
        return torch.zeros_like(positions)
    return -gradient


class MACEFNOResidual(nn.Module):
    """Add a learned conservative particle-mesh residual to frozen MACE.

    By default atom features are assigned to the original 2D mesh. Supplying
    ``z_grid_size`` and ``z_extent`` selects the hybrid 2.5D path for backward
    compatibility. Explicitly setting ``spatial_scheme='3d'`` instead selects a
    fully periodic bulk mesh and 3D Fourier operator. All graphs in a MACE batch
    are deposited and transformed together.
    """

    def __init__(
        self,
        mace_model: nn.Module,
        grid_shape: tuple[int, int],
        channels: int,
        n_modes: tuple[int, int],
        *,
        source_hidden_channels: int = 64,
        fno_hidden_channels: int = 32,
        fno_layers: int = 4,
        fno_projection_channels: int | None = None,
        fno_architecture: str = "nonlinear",
        spatial_scheme: str | None = None,
        z_grid_size: int | None = None,
        fno_z_modes: int | None = None,
        z_extent: float | None = None,
        z_center: str = "mean",
        fno_lateral_interlacing: int = 1,
        fno_volume_interlacing: int = 1,
        fno_interlacing_training: str = "full",
        fno_z_kernel_size: int = 3,
        fno_z_mixing: str = "local",
        fno_planar_symmetry: str = "none",
        fno_spectral_symmetry: str = "none",
        fno_spectral_groups: int = 1,
        invariant_indices: Sequence[int] | None = None,
        reference_cell: Tensor | None = None,
        cell_tolerance: float = 1.0e-6,
        cell_mode: str = "fixed",
    ) -> None:
        super().__init__()
        self.backbone = FrozenMACEFeatures(
            mace_model, invariant_indices=invariant_indices
        )
        self.source_head = NeutralLatentHead(
            self.backbone.feature_dim,
            channels,
            hidden_channels=source_hidden_channels,
        )
        if spatial_scheme is None:
            resolved_scheme = "2.5d" if z_grid_size is not None else "2d"
        else:
            resolved_scheme = str(spatial_scheme).lower()
            if resolved_scheme not in {"2d", "2.5d", "3d"}:
                raise ValueError("spatial_scheme must be '2d', '2.5d', or '3d'")
        if resolved_scheme != "3d" and fno_z_modes is not None:
            raise ValueError("fno_z_modes applies only to spatial_scheme='3d'")
        if resolved_scheme != "2.5d" and fno_lateral_interlacing != 1:
            raise ValueError("fno_lateral_interlacing applies only to the 2.5D scheme")
        if resolved_scheme != "3d" and fno_volume_interlacing != 1:
            raise ValueError("fno_volume_interlacing applies only to the 3D scheme")
        if resolved_scheme != "2.5d" and fno_planar_symmetry != "none":
            raise ValueError("fno_planar_symmetry applies only to the 2.5D scheme")
        if fno_spectral_symmetry not in {
            "none",
            "eqgino",
            "cubic_adaptive",
        }:
            raise ValueError(
                "fno_spectral_symmetry must be 'none', 'eqgino', or "
                "'cubic_adaptive'"
            )
        if resolved_scheme != "3d" and fno_spectral_symmetry != "none":
            raise ValueError("fno_spectral_symmetry applies only to the 3D scheme")
        if fno_spectral_groups < 1:
            raise ValueError("fno_spectral_groups must be positive")
        if fno_spectral_symmetry == "none" and fno_spectral_groups != 1:
            raise ValueError(
                "fno_spectral_groups applies only to EqGINO-based symmetry"
            )
        if cell_mode not in {"fixed", "isotropic", "anisotropic"}:
            raise ValueError(
                "cell_mode must be 'fixed', 'isotropic', or 'anisotropic'"
            )
        if cell_mode != "fixed" and resolved_scheme != "3d":
            raise ValueError(
                "variable-cell modes apply only to the fully periodic 3D scheme"
            )
        if cell_mode != "fixed" and fno_architecture != "nonlinear":
            raise ValueError("variable-cell mode requires a nonlinear FNO")
        if cell_mode == "anisotropic" and fno_spectral_symmetry == "eqgino":
            raise ValueError(
                "anisotropic cell mode is incompatible with cubic EqGINO symmetry"
            )

        if resolved_scheme == "2d":
            if z_grid_size is not None:
                raise ValueError("z_grid_size is incompatible with spatial_scheme='2d'")
            if z_extent is not None:
                raise ValueError("z_extent requires z_grid_size")
            if fno_z_mixing != "local":
                raise ValueError("global z mixing requires z_grid_size")
            self.long_range = LearnedParticleMeshLongRange(
                grid_shape,
                channels,
                n_modes,
                hidden_channels=fno_hidden_channels,
                n_layers=fno_layers,
                projection_channels=fno_projection_channels,
                architecture=fno_architecture,
                check_neutrality=False,
            )
            self.spatial_scheme = "2d"
        elif resolved_scheme == "2.5d":
            if z_grid_size is None:
                raise ValueError("z_grid_size is required for spatial_scheme='2.5d'")
            if z_extent is None:
                raise ValueError("z_extent is required when z_grid_size is set")
            self.long_range = LearnedParticleMeshLongRange2p5D(
                (int(z_grid_size), *grid_shape),
                z_extent,
                channels,
                n_modes,
                z_center=z_center,
                lateral_interlacing=fno_lateral_interlacing,
                z_kernel_size=fno_z_kernel_size,
                z_mixing=fno_z_mixing,
                planar_symmetry=fno_planar_symmetry,
                hidden_channels=fno_hidden_channels,
                n_layers=fno_layers,
                projection_channels=fno_projection_channels,
                architecture=fno_architecture,
                check_neutrality=False,
            )
            self.spatial_scheme = "2.5d"
        else:
            if z_grid_size is None:
                raise ValueError("z_grid_size is required for spatial_scheme='3d'")
            if z_extent is not None:
                raise ValueError("z_extent is incompatible with fully periodic 3D FNO")
            if fno_z_mixing != "local":
                raise ValueError("fno_z_mixing applies only to the 2.5D scheme")
            z_modes = int(fno_z_modes) if fno_z_modes is not None else int(n_modes[0])
            if z_modes < 1:
                raise ValueError("fno_z_modes must be positive")
            if fno_spectral_symmetry in {"eqgino", "cubic_adaptive"}:
                if not (
                    int(z_grid_size) == int(grid_shape[0]) == int(grid_shape[1])
                ):
                    raise ValueError("EqGINO-based symmetry requires a cubic 3D grid")
                if not (z_modes == int(n_modes[0]) == int(n_modes[1])):
                    raise ValueError(
                        "EqGINO-based symmetry requires equal modes on all axes"
                    )
            self.long_range = LearnedParticleMeshLongRange3D(
                (int(z_grid_size), *grid_shape),
                channels,
                (z_modes, *n_modes),
                hidden_channels=fno_hidden_channels,
                n_layers=fno_layers,
                projection_channels=fno_projection_channels,
                architecture=fno_architecture,
                spectral_symmetry=fno_spectral_symmetry,
                spectral_groups=fno_spectral_groups,
                cell_conditioning=(
                    cell_mode if cell_mode in {"isotropic", "anisotropic"} else "none"
                ),
                volume_interlacing=fno_volume_interlacing,
                interlacing_training=fno_interlacing_training,
                check_neutrality=False,
            )
            self.spatial_scheme = "3d"
        if reference_cell is None:
            reference_cell = torch.empty(0)
        elif reference_cell.shape != (3, 3):
            raise ValueError("reference_cell must have shape (3, 3)")
        if (
            fno_spectral_symmetry == "eqgino"
            and reference_cell.numel() != 0
            and not is_cubic_cell(reference_cell)
        ):
            raise ValueError("EqGINO symmetry requires a cubic reference_cell")
        self.register_buffer("reference_cell", reference_cell.detach().clone())
        self.fno_spectral_symmetry = fno_spectral_symmetry
        self.cell_tolerance = float(cell_tolerance)
        self.cell_mode = cell_mode

    def _validate_cells(self, cells: Tensor) -> None:
        if self.fno_spectral_symmetry == "eqgino":
            if any(not is_cubic_cell(cell) for cell in cells):
                raise ValueError("EqGINO symmetry requires cubic cells")
        if self.cell_mode == "anisotropic":
            determinants = torch.linalg.det(cells)
            valid = torch.isfinite(cells).all(dim=(-2, -1)) & torch.isfinite(
                determinants
            )
            valid = valid & (determinants.abs() > torch.finfo(cells.dtype).eps)
            if not bool(valid.all().detach().cpu()):
                raise ValueError(
                    "anisotropic cell mode requires finite, nonsingular cells"
                )
            return
        if self.reference_cell.numel() == 0:
            return
        reference = self.reference_cell.to(dtype=cells.dtype, device=cells.device)
        if self.cell_mode == "isotropic":
            reference_norm = reference.square().sum()
            if bool((reference_norm <= 0).detach().cpu()):
                raise ValueError("reference_cell must have positive volume")
            scales = torch.einsum("bij,ij->b", cells, reference) / reference_norm
            residual = cells - scales[:, None, None] * reference
            error = residual.abs().amax(dim=(-2, -1))
            cell_scale = cells.abs().amax(dim=(-2, -1)).clamp_min(1.0)
            invalid = (scales <= 0) | (error > self.cell_tolerance * cell_scale)
            if bool(invalid.any().detach().cpu()):
                raise ValueError(
                    "isotropic cell mode requires every cell to be a positive "
                    "uniform scaling of reference_cell"
                )
            if any(not is_cubic_cell(cell) for cell in cells):
                raise ValueError("isotropic cell mode requires cubic cells")
            return
        # Planar/slab operators depend only on the first two vectors, whereas
        # the bulk operator uses all three reciprocal lattice directions.
        compared_cells = cells if self.spatial_scheme == "3d" else cells[:, :2]
        compared_reference = reference if self.spatial_scheme == "3d" else reference[:2]
        maximum_error = (compared_cells - compared_reference).abs().max()
        scale = compared_reference.abs().max().clamp_min(1.0)
        if bool((maximum_error > self.cell_tolerance * scale).detach().cpu()):
            raise ValueError(
                "FNOFieldOperator is fixed-cell, but a cell differs from "
                "reference_cell beyond cell_tolerance"
            )

    def forward(
        self,
        data: Mapping[str, Tensor],
        *,
        training: bool | None = None,
        compute_force: bool = True,
        compute_residual_force: bool = False,
        compute_base_force: bool = False,
        return_fields: bool = False,
    ) -> dict[str, Any]:
        if "positions" not in data or "cell" not in data:
            raise KeyError("data must contain positions and cell")
        positions = data["positions"]
        if not torch.is_grad_enabled() and (
            compute_force or compute_residual_force or compute_base_force
        ):
            raise RuntimeError(
                "force evaluation requires PyTorch gradients to be enabled"
            )

        base_energy, invariants, mace_output = self.backbone(data)
        batch = data.get(
            "batch",
            torch.zeros(positions.shape[0], dtype=torch.long, device=positions.device),
        )
        if batch.dtype != torch.long:
            batch = batch.to(torch.long)
        num_graphs = int(batch.max().detach().cpu()) + 1
        cells = _graph_cells(data["cell"], num_graphs)
        self._validate_cells(cells)
        sources = self.source_head(invariants, batch)

        result = self.long_range(
            positions,
            sources,
            cells,
            batch=batch,
            return_fields=return_fields,
        )
        if return_fields:
            residual_energy, density_batch, potential_batch = result
            densities = list(density_batch.unbind(0))
            potentials = list(potential_batch.unbind(0))
        else:
            residual_energy = result
            densities = []
            potentials = []
        if base_energy.shape != residual_energy.shape:
            raise ValueError(
                "MACE energy shape must match one scalar per graph; received "
                f"{tuple(base_energy.shape)} for {num_graphs} graphs"
            )
        total_energy = base_energy + residual_energy
        create_graph = self.training if training is None else bool(training)

        forces = None
        residual_forces = None
        base_forces = None
        if compute_force:
            forces = _negative_energy_gradient(
                total_energy,
                positions,
                create_graph=create_graph,
                retain_graph=(
                    compute_residual_force or compute_base_force or create_graph
                ),
            )
        if compute_residual_force:
            residual_forces = _negative_energy_gradient(
                residual_energy,
                positions,
                create_graph=create_graph,
                retain_graph=compute_base_force or create_graph,
            )
        if compute_base_force:
            base_forces = _negative_energy_gradient(
                base_energy,
                positions,
                create_graph=create_graph,
                retain_graph=create_graph,
            )

        return {
            "energy": total_energy,
            "forces": forces,
            "base_energy": base_energy,
            "base_forces": base_forces,
            "residual_energy": residual_energy,
            "residual_forces": residual_forces,
            "invariant_features": invariants,
            "sources": sources,
            "density": densities if return_fields else None,
            "potential": potentials if return_fields else None,
            "mace_output": mace_output,
        }


def energy_force_loss(
    predicted_energy: Tensor,
    predicted_forces: Tensor,
    target_energy: Tensor,
    target_forces: Tensor,
    batch: Tensor,
    *,
    energy_weight: float = 1.0,
    force_weight: float = 1.0,
    energy_scale: float = 1.0,
    force_scale: float = 1.0,
) -> dict[str, Tensor]:
    """Per-atom energy MSE plus Cartesian force-component MSE."""
    if predicted_energy.shape != target_energy.shape:
        raise ValueError("predicted and target energies must have matching shapes")
    if predicted_forces.shape != target_forces.shape:
        raise ValueError("predicted and target forces must have matching shapes")
    if min(energy_scale, force_scale) <= 0:
        raise ValueError("energy_scale and force_scale must be positive")
    num_graphs = predicted_energy.numel()
    counts = predicted_forces.new_zeros(num_graphs).index_add(
        0, batch, predicted_forces.new_ones(batch.shape[0])
    )
    energy_error = (predicted_energy - target_energy) / counts / float(energy_scale)
    force_error = (predicted_forces - target_forces) / float(force_scale)
    energy_loss = energy_error.square().mean()
    force_loss = force_error.square().mean()
    total = float(energy_weight) * energy_loss + float(force_weight) * force_loss
    return {"loss": total, "energy": energy_loss, "forces": force_loss}
